In [1]:
import pandas as pd
import numpy as np
import keras

from keras.models import Sequential
from keras.layers import Dense

# load the concrete_data dataset
concrete_data = pd.read_csv('https://cocl.us/concrete_data')

# verify that the data was loaded correctly
concrete_data.head()

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [2]:
# split the concrete_data set into predictors (inputs) and target (output)
predictors = concrete_data.drop(columns=['Strength'])
target = concrete_data['Strength']

n_cols = predictors.shape[1]

In [3]:
def regression_model():
    model = Sequential()
    model.add(Dense(10, activation = 'relu', input_shape=(n_cols,)))
    model.add(Dense(1)) ##
    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    
    return model

model = regression_model()

In [4]:
from sklearn.model_selection import train_test_split

predictors_train, predictors_test, target_train, target_test = train_test_split(
    predictors, target, test_size = 0.3, random_state = 71)

predictors_train.shape

(721, 8)

In [5]:
model.fit(predictors_train, target_train, epochs=50)

Epoch 1/50
721/721 [==============================] - 1s 2ms/step - loss: 55536.3644
Epoch 2/50
721/721 [==============================] - 1s 1ms/step - loss: 10814.5337
Epoch 3/50
721/721 [==============================] - 1s 1ms/step - loss: 2852.1250
Epoch 4/50
721/721 [==============================] - 1s 1ms/step - loss: 2513.9944
Epoch 5/50
721/721 [==============================] - 1s 694us/step - loss: 2269.4027
Epoch 6/50
721/721 [==============================] - 0s 615us/step - loss: 2045.6548
Epoch 7/50
721/721 [==============================] - 1s 796us/step - loss: 1843.5201
Epoch 8/50
721/721 [==============================] - 1s 860us/step - loss: 1653.0159
Epoch 9/50
721/721 [==============================] - 1s 887us/step - loss: 1484.5305
Epoch 10/50
721/721 [==============================] - 1s 1ms/step - loss: 1329.2414
Epoch 11/50
721/721 [==============================] - 1s 892us/step - loss: 1191.19500s -
Epoch 12/50
721/721 [==============================] - 1s 966us/step - loss: 1069.7555
Epoch 13/50
721/721 [==============================] - 1s 1ms/step - loss: 965.1249
Epoch 14/50
721/721 [==============================] - 1s 770us/step - loss: 875.1844
Epoch 15/50
721/721 [==============================] - 1s 1ms/step - loss: 794.0130
Epoch 16/50
721/721 [==============================] - 1s 775us/step - loss: 725.1156
Epoch 17/50
721/721 [==============================] - 1s 776us/step - loss: 665.5669
Epoch 18/50
721/721 [==============================] - 0s 692us/step - loss: 616.4185
Epoch 19/50
721/721 [==============================] - 1s 914us/step - loss: 573.0112
Epoch 20/50
721/721 [==============================] - 1s 803us/step - loss: 534.4932
Epoch 21/50
721/721 [==============================] - 1s 1ms/step - loss: 503.0774
Epoch 22/50
721/721 [==============================] - 1s 1ms/step - loss: 473.7938
Epoch 23/50
721/721 [==============================] - 1s 1ms/step - loss: 449.5064
Epoch 24/50
721/721 [==============================] - 1s 696us/step - loss: 427.1387
Epoch 25/50
721/721 [==============================] - 1s 936us/step - loss: 405.7651 0s - loss: 388
Epoch 26/50
721/721 [==============================] - 1s 723us/step - loss: 388.2217
Epoch 27/50
721/721 [==============================] - 1s 940us/step - loss: 370.9358
Epoch 28/50
721/721 [==============================] - 1s 861us/step - loss: 356.7931
Epoch 29/50
721/721 [==============================] - 1s 999us/step - loss: 340.3651
Epoch 30/50
721/721 [==============================] - 1s 775us/step - loss: 325.5116
Epoch 31/50
721/721 [==============================] - 1s 2ms/step - loss: 314.5608
Epoch 32/50
721/721 [==============================] - 1s 812us/step - loss: 301.1636
Epoch 33/50
721/721 [==============================] - 1s 744us/step - loss: 289.7331
Epoch 34/50
721/721 [==============================] - 1s 916us/step - loss: 277.4346
Epoch 35/50
721/721 [==============================] - 1s 1ms/step - loss: 265.7234
Epoch 36/50
721/721 [==============================] - 1s 694us/step - loss: 255.8729
Epoch 37/50
721/721 [==============================] - 1s 804us/step - loss: 247.1256
Epoch 38/50
721/721 [==============================] - 1s 803us/step - loss: 236.5382
Epoch 39/50
721/721 [==============================] - 1s 858us/step - loss: 228.0631
Epoch 40/50
721/721 [==============================] - 0s 580us/step - loss: 219.7554
Epoch 41/50
721/721 [==============================] - 0s 497us/step - loss: 211.8716
Epoch 42/50
721/721 [==============================] - 0s 612us/step - loss: 205.0028
Epoch 43/50
721/721 [==============================] - 0s 499us/step - loss: 198.3659
Epoch 44/50
721/721 [==============================] - 0s 606us/step - loss: 194.1407
Epoch 45/50
721/721 [==============================] - 0s 558us/step - loss: 184.8762
Epoch 46/50
721/721 [==============================] - 0s 637us/step - loss: 180.4684
Epoch 47/50
721/721 [==============================] - 0s 636us/step - loss: 174.1047
Epoch 48/50
721/721 [==============================] - 1s 775us/step - loss: 169.2096
Epoch 49/50
721/721 [==============================] - 1s 722us/step - loss: 166.1038
Epoch 50/50
721/721 [==============================] - 1s 748us/step - loss: 160.0931

In [6]:
from sklearn.metrics import mean_squared_error

In [7]:
predictions_test = model.predict(predictors_test)
print("Mean squared error on test data is %.3f" % 
      (mean_squared_error(target_test, predictions_test)))

Mean squared error on test data is 152.724

In [8]:
def evaluate_model(create_model_func, predictors, targets, epochs = 50):
    mean_squared_errors =[]
    for i in range(50):
        #Road the model
        model = create_model_func()
        
        #Split data into train and test
        predictors_train, predictors_test, target_train, target_test = train_test_split(
        predictors, target, test_size=0.3, random_state = 70)
        
        #Train 50 epochs
        model.fit(predictors_train, target_train, epochs = epochs, verbose=0)
        
        #Measure the mse and add this to the list
        predictions_test = model.predict(predictors_test)
        mse = mean_squared_error(target_test, predictions_test)
        mean_squared_errors.append(mse)
        print('...', end='')
    print('Done!')
    
    return np.mean(mean_squared_errors), np.std(mean_squared_errors)

In [10]:
#Normalize the data
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
#PartC
#Repeat B but use 100 epochs for training the model

mean_mse, std_mse = evaluate_model(regression_model, predictors_norm, target, 
                                  epochs = 100)
print("Mean squared errors for regression models on normalized data,trained 100epochs : mean = %.3f, std = %.3f"
     % (mean_mse, std_mse))

......................................................................................................................................................Done!
Mean squared errors for regression models on normalized data,trained 100epochs : mean = 160.124, std = 16.107